//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class GeoLocation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GeoLocation()
        {
            this.PopularLocationItems = new HashSet<PopularLocationItem>();
        }
    
        public int IDGeoLocation { get; set; }
        public string Name { get; set; }
        public decimal PositionX { get; set; }
        public decimal PositionY { get; set; }
        public Nullable<int> CityID { get; set; }
        [JsonIgnore]
        public virtual City City { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<PopularLocationItem> PopularLocationItems { get; set; }
    }
}
