//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class oicartim04dbEntities : DbContext
    {
        public oicartim04dbEntities()
            : base("name=oicartim04dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccomodationItem> AccomodationItems { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<GeoLocation> GeoLocations { get; set; }
        public virtual DbSet<Picture> Pictures { get; set; }
        public virtual DbSet<PopularLocationItem> PopularLocationItems { get; set; }
        public virtual DbSet<QRCode> QRCodes { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<WalletItem> WalletItems { get; set; }
    }
}
