//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Picture
    {
        public int IDPicture { get; set; }
        public string Name { get; set; }
        public string ContentType { get; set; }
        public byte[] Content { get; set; }
        public string PicturePath { get; set; }
        public Nullable<int> AccomodationID { get; set; }
        public Nullable<int> PopularLocationID { get; set; }
        public Nullable<int> WalletID { get; set; }
        [JsonIgnore]
        public virtual AccomodationItem AccomodationItem { get; set; }
        [JsonIgnore]
        public virtual PopularLocationItem PopularLocationItem { get; set; }
        [JsonIgnore]
        public virtual WalletItem WalletItem { get; set; }
    }
}
