//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class PopularLocationItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PopularLocationItem()
        {
            this.Pictures = new HashSet<Picture>();
        }
    
        public int IDPopularLocationItem { get; set; }
        public string Description { get; set; }
        public Nullable<int> GeoLocationID { get; set; }
        public Nullable<int> QRCodeID { get; set; }
        public bool IsVisited { get; set; }
        [JsonIgnore]
        public virtual GeoLocation GeoLocation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        
        public virtual ICollection<Picture> Pictures { get; set; }
        [JsonIgnore]
        public virtual QRCode QRCode { get; set; }
    }
}
