//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.QRCodes = new HashSet<QRCode>();
        }
    
        public int IDUser { get; set; }
        public string Username { get; set; }
        public string Email { get; set; }
        public byte[] Pass { get; set; }
        public bool IsAdmin { get; set; }
        public bool IsDeleted { get; set; }

        public string Token { get; set; } 


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<QRCode> QRCodes { get; set; }

        public override string ToString()
        {
            return Username + " ," + Pass + " ," + IDUser + " ," + IsAdmin + " ," + Email;
        }
    }
}
